# Comparando, Tratando e Mesclando DataFrames

## Objetivo

Vamos modificar os IDs para os nomes dos produtos, dos clientes e das lojas, para nossas análises ficarem mais intuitivas futuramente. Para isso, vamos criar um data frame com todos os detalhes.

- Usaremos o método merge para isso e, depois se quisermos, podemos pegar apenas as colunas que queremos do dataframe final.

### Criando nossos dataframes

In [2]:
import pandas as pd

#às vezes precisaremos mudar o encoding. Possiveis valores para testar:
#encoding='latin1', encoding='ISO-8859-1', encoding='utf-8' ou então encoding='cp1252'
vendas_df = pd.read_csv(r'Contoso - Vendas - 2017.csv', sep=';')
promocoes = pd.read_csv(r'Contoso - Promocoes.csv', sep=';', encoding='cp1252')
loja = pd.read_csv(r'Contoso - Lojas.csv', sep=';', encoding='cp1252')
clientes = pd.read_csv(r'Contoso - Clientes.csv', sep=';', encoding='cp1252')
cadastro_produtos = pd.read_csv(r'Contoso - Cadastro Produtos.csv', sep=';', encoding='cp1252')


#usaremos o display para ver todos os dataframes
display(vendas_df)
display(promocoes)
display(loja)
display(clientes)
display(cadastro_produtos)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1
...,...,...,...,...,...,...,...,...,...,...
980637,980638,31/12/2017,31/12/2017,0,194,2490,4,10353,120,0
980638,980639,31/12/2017,06/01/2018,6,32,2488,4,31750,120,0
980639,980640,31/12/2017,03/01/2018,3,210,2511,10,12003,80,0
980640,980641,31/12/2017,31/12/2017,0,53,436,4,25550,39,0
980641,980642,31/12/2017,31/12/2017,0,309,2510,10,28707,80,0

,ÿID Promocao,Nome Promocao,Percentual Desconto,Data Inicio,Data Termino,Unnamed: 5,Unnamed: 6
0,1,Sem desconto,0,01/01/2017,31/12/2020,NaN,NaN
1,2,Promoção de Primavera Americana,"0,05",01/01/2017,31/03/2017,NaN,NaN
2,3,Promoção Volta às Aulas Americanas,"0,1",01/07/2017,30/09/2017,NaN,NaN
3,4,Promoção Férias Escolares Americanas,"0,2",01/11/2017,31/12/2017,NaN,NaN
4,5,Promoção Férias Asiáticas,"0,15",01/11/2017,31/01/2018,NaN,NaN
5,6,Promoção de Primavera Asiática,"0,2",01/02/2017,30/04/2017,NaN,NaN
6,7,Promoção de Verão Asiático,"0,1",01/05/2017,30/06/2017,NaN,NaN
7,8,Promoção de Primavera Europeia,"0,07",01/02/2017,30/04/2017,NaN,NaN
8,9,Promoção Volta às Aulas Europeias,"0,1",01/08/2017,30/09/2017,NaN,NaN
9,10,Promoção de Férias Europeias,"0,2",01/10/2017,31/01/2018,NaN,NaN
10,11,Promoção de Primavera Americana,"0,05",01/01/2018,31/03/2018,NaN,NaN
11,12,Promoção Volta às Aulas Americanas,"0,1",01/07/2018,30/09/2018,NaN,NaN
12,13,Promoção Férias Escolares Americanas,"0,2",01/11/2018,31/12/2018,NaN,NaN
13,14,Promoção Férias Asiáticas,"0,15",01/11/2018,31/01/2019,NaN,NaN
14,15,Promoção de Primavera Asiática,"0,2",01/02/2018,30/04/2018,NaN,NaN
15,16,Promoção de Verão Asiático,"0,1",01/05/2018,30/06/2018,NaN,NaN
16,17,Promoção de Primavera Europeia,"0,07",01/02/2018,30/04/2018,NaN,NaN
17,18,Promoção Volta às Aulas Europeias,"0,1",01/08/2018,30/09/2018,NaN,NaN
18,19,Promoção de Férias Europeias,"0,2",01/10/2018,31/01/2019,NaN,NaN
19,20,Promoção de Primavera Americana,"0,05",01/01/2019,31/03/2020,NaN,NaN
20,21,Promoção Volta às Aulas Americanas,"0,1",01/07/2019,30/09/2019,NaN,NaN
21,22,Promoção Férias Escolares Americanas,"0,2",01/11/2019,31/12/2019,NaN,NaN
22,23,Promoção Férias Asiáticas,"0,15",01/11/2019,31/01/2020,NaN,NaN
23,24,Promoção de Primavera Asiática,"0,2",01/02/2019,30/04/2019,NaN,NaN
24,25,Promoção de Verão Asiático,"0,1",01/05/2019,30/06/2019,NaN,NaN
25,26,Promoção de Primavera Europeia,"0,07",01/02/2019,30/04/2019,NaN,NaN
26,27,Promoção Volta às Aulas Europeias,"0,1",01/08/2019,30/09/2019,NaN,NaN
27,28,Promoção de Férias Europeias,"0,2",01/10/2019,31/01/2020,NaN,NaN

,ÿID Loja,Nome da Loja,Quantidade Colaboradores,País
0,1,Loja Contoso Seattle No.1,17.0,Estados Unidos
1,2,Loja Contoso Seattle No.2,25.0,Estados Unidos
2,3,Loja Contoso Kennewick,26.0,Estados Unidos
3,4,Loja Contoso Bellevue,19.0,Estados Unidos
4,5,Loja Contoso Redmond,33.0,Estados Unidos
...,...,...,...,...
301,306,Loja Contoso Europe Online,7.0,Alemanha
302,307,Loja Contoso Asia Online,8.0,China
303,308,Loja Contoso North America Reseller,15.0,Estados Unidos
304,309,Loja Contoso Europe Reseller,12.0,França
305,310,Loja Contoso Asia Reseller,17.0,China

,ÿID Cliente,Primeiro Nome,Sobrenome,E-mail,Genero,Numero de Filhos,Data de Nascimento,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,Garnet,Lanfranchi,glanfranchi0@mayoclinic.com,Feminino,2,12/05/1995,NaN,NaN,NaN,NaN
1,2,Lurette,Roseblade,lroseblade1@bigcartel.com,Feminino,2,30/06/1943,NaN,NaN,NaN,NaN
2,3,Glenden,Ishchenko,gishchenko2@moonfruit.com,Masculino,5,09/04/1989,NaN,NaN,NaN,NaN
3,4,Baron,Jedrzejewsky,bjedrzejewsky3@e-recht24.de,Masculino,4,17/11/1998,NaN,NaN,NaN,NaN
4,5,Sheree,Bredbury,sbredbury4@sitemeter.com,Feminino,5,08/09/1975,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
39499,39500,Brandy,Malhotra,brandy0@adventure-works.com,Masculino,3,27/07/1980,NaN,NaN,NaN,NaN
39500,39501,Alicia,Raje,alicia12@adventure-works.com,Feminino,5,10/05/2001,NaN,NaN,NaN,NaN
39501,39502,Connie,Rai,connie4@adventure-works.com,Feminino,0,13/02/1997,NaN,NaN,NaN,NaN
39502,39503,Shawn,Raji,shawn23@adventure-works.com,Masculino,1,29/03/2001,NaN,NaN,NaN,NaN
39503,39504,Lindsey,Sharma,lindsey10@adventure-works.com,Feminino,0,19/11/1961,NaN,NaN,NaN,NaN

,ÿNome do Produto,Descricao do Produto,Fabricante,Nome da Marca,Tipo,Custo Unitario,Preco Unitario,ID Produto,ID Subcategoria
0,Contoso Wireless Laser Mouse E50 Grey,Advanced 2.4 GHz cordless technology makes fre...,"Contoso, Ltd",Contoso,Econômico,"10,69","20,96",873,22
1,Contoso Optical Wheel OEM PS/2 Mouse E60 Grey,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,879,22
2,Contoso Optical Wheel OEM PS/2 Mouse E60 Black,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,880,22
3,Contoso Optical Wheel OEM PS/2 Mouse E60 White,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,881,22
4,Contoso Optical Wheel OEM PS/2 Mouse E60 Silver,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,882,22
...,...,...,...,...,...,...,...,...,...
1685,SV DVD 12-Inch Player Portable M400 Black,"6-hour rechargeable battery, 180-degree swivel...",Southridge Video,Southridge Video,Regular,"82,77","179,99",1602,35
1686,SV DVD 9-Inch Player Portable M300 Silver,"6-hour rechargeable battery, 180-degree swivel...",Southridge Video,Southridge Video,Regular,"73,57","159,99",1606,35
1687,SV DVD 12-Inch Player Portable M400 Silver,"6-hour rechargeable battery, 180-degree swivel...",Southridge Video,Southridge Video,Regular,"82,77","179,99",1607,35
1688,SV DVD 9-Inch Player Portable M300 White,"6-hour rechargeable battery, 180-degree swivel...",Southridge Video,Southridge Video,Regular,"73,57","159,99",1611,35
1689,SV DVD 12-Inch Player Portable M400 White,"6-hour rechargeable battery, 180-degree swivel...",Southridge Video,Southridge Video,Regular,"82,77","179,99",1612,35

### Vamos tirar as colunas inúteis do clientes_df ou pegar apenas as colunas que quisermos

.drop([coluna1, coluna2, coluna3]) -> retira as colunas: coluna1, coluna2, coluna3

In [3]:
promocoes = promocoes.drop(['Unnamed: 5', 'Unnamed: 6'], axis=1)

### Agora vamos juntar os dataframes para ter 1 único dataframe com tudo "bonito"

novo_dataframe = dataframe1.merge(dataframe2, on='coluna')

- Obs: O merge precisa das colunas com o mesmo nome para funcionar. Se não tiver, você precisa alterar o nome da coluna com o .rename

dataframe.rename({'coluna1': 'novo_coluna_1'})

In [ ]:
#juntando os dataframes
promocoes = promocoes.rename({'ÿID Promocao': 'ID Produto'})
clientes = promocoes.rename({'ÿID Cliente': 'ID Cliente'})
loja = promocoes.rename({'ÿID Loja': 'ID Loja'})

display(promocoes)
display(clientes)
display(loja)

# vendas_df = vendas_df.merge(promocoes, on='ID Produto')
# vendas_df = vendas_df.merge(loja, on='ID Loja')
# vendas_df = vendas_df.merge(clientes, on='ID Cliente')

# # exibindo o dataframe final
# display(vendas_df)

,ÿID Promocao,Nome Promocao,Percentual Desconto,Data Inicio,Data Termino
0,1,Sem desconto,0,01/01/2017,31/12/2020
1,2,Promoção de Primavera Americana,"0,05",01/01/2017,31/03/2017
2,3,Promoção Volta às Aulas Americanas,"0,1",01/07/2017,30/09/2017
3,4,Promoção Férias Escolares Americanas,"0,2",01/11/2017,31/12/2017
4,5,Promoção Férias Asiáticas,"0,15",01/11/2017,31/01/2018
5,6,Promoção de Primavera Asiática,"0,2",01/02/2017,30/04/2017
6,7,Promoção de Verão Asiático,"0,1",01/05/2017,30/06/2017
7,8,Promoção de Primavera Europeia,"0,07",01/02/2017,30/04/2017
8,9,Promoção Volta às Aulas Europeias,"0,1",01/08/2017,30/09/2017
9,10,Promoção de Férias Europeias,"0,2",01/10/2017,31/01/2018
10,11,Promoção de Primavera Americana,"0,05",01/01/2018,31/03/2018
11,12,Promoção Volta às Aulas Americanas,"0,1",01/07/2018,30/09/2018
12,13,Promoção Férias Escolares Americanas,"0,2",01/11/2018,31/12/2018
13,14,Promoção Férias Asiáticas,"0,15",01/11/2018,31/01/2019
14,15,Promoção de Primavera Asiática,"0,2",01/02/2018,30/04/2018
15,16,Promoção de Verão Asiático,"0,1",01/05/2018,30/06/2018
16,17,Promoção de Primavera Europeia,"0,07",01/02/2018,30/04/2018
17,18,Promoção Volta às Aulas Europeias,"0,1",01/08/2018,30/09/2018
18,19,Promoção de Férias Europeias,"0,2",01/10/2018,31/01/2019
19,20,Promoção de Primavera Americana,"0,05",01/01/2019,31/03/2020
20,21,Promoção Volta às Aulas Americanas,"0,1",01/07/2019,30/09/2019
21,22,Promoção Férias Escolares Americanas,"0,2",01/11/2019,31/12/2019
22,23,Promoção Férias Asiáticas,"0,15",01/11/2019,31/01/2020
23,24,Promoção de Primavera Asiática,"0,2",01/02/2019,30/04/2019
24,25,Promoção de Verão Asiático,"0,1",01/05/2019,30/06/2019
25,26,Promoção de Primavera Europeia,"0,07",01/02/2019,30/04/2019
26,27,Promoção Volta às Aulas Europeias,"0,1",01/08/2019,30/09/2019
27,28,Promoção de Férias Europeias,"0,2",01/10/2019,31/01/2020

,ÿID Promocao,Nome Promocao,Percentual Desconto,Data Inicio,Data Termino
0,1,Sem desconto,0,01/01/2017,31/12/2020
1,2,Promoção de Primavera Americana,"0,05",01/01/2017,31/03/2017
2,3,Promoção Volta às Aulas Americanas,"0,1",01/07/2017,30/09/2017
3,4,Promoção Férias Escolares Americanas,"0,2",01/11/2017,31/12/2017
4,5,Promoção Férias Asiáticas,"0,15",01/11/2017,31/01/2018
5,6,Promoção de Primavera Asiática,"0,2",01/02/2017,30/04/2017
6,7,Promoção de Verão Asiático,"0,1",01/05/2017,30/06/2017
7,8,Promoção de Primavera Europeia,"0,07",01/02/2017,30/04/2017
8,9,Promoção Volta às Aulas Europeias,"0,1",01/08/2017,30/09/2017
9,10,Promoção de Férias Europeias,"0,2",01/10/2017,31/01/2018
10,11,Promoção de Primavera Americana,"0,05",01/01/2018,31/03/2018
11,12,Promoção Volta às Aulas Americanas,"0,1",01/07/2018,30/09/2018
12,13,Promoção Férias Escolares Americanas,"0,2",01/11/2018,31/12/2018
13,14,Promoção Férias Asiáticas,"0,15",01/11/2018,31/01/2019
14,15,Promoção de Primavera Asiática,"0,2",01/02/2018,30/04/2018
15,16,Promoção de Verão Asiático,"0,1",01/05/2018,30/06/2018
16,17,Promoção de Primavera Europeia,"0,07",01/02/2018,30/04/2018
17,18,Promoção Volta às Aulas Europeias,"0,1",01/08/2018,30/09/2018
18,19,Promoção de Férias Europeias,"0,2",01/10/2018,31/01/2019
19,20,Promoção de Primavera Americana,"0,05",01/01/2019,31/03/2020
20,21,Promoção Volta às Aulas Americanas,"0,1",01/07/2019,30/09/2019
21,22,Promoção Férias Escolares Americanas,"0,2",01/11/2019,31/12/2019
22,23,Promoção Férias Asiáticas,"0,15",01/11/2019,31/01/2020
23,24,Promoção de Primavera Asiática,"0,2",01/02/2019,30/04/2019
24,25,Promoção de Verão Asiático,"0,1",01/05/2019,30/06/2019
25,26,Promoção de Primavera Europeia,"0,07",01/02/2019,30/04/2019
26,27,Promoção Volta às Aulas Europeias,"0,1",01/08/2019,30/09/2019
27,28,Promoção de Férias Europeias,"0,2",01/10/2019,31/01/2020

,ÿID Promocao,Nome Promocao,Percentual Desconto,Data Inicio,Data Termino
0,1,Sem desconto,0,01/01/2017,31/12/2020
1,2,Promoção de Primavera Americana,"0,05",01/01/2017,31/03/2017
2,3,Promoção Volta às Aulas Americanas,"0,1",01/07/2017,30/09/2017
3,4,Promoção Férias Escolares Americanas,"0,2",01/11/2017,31/12/2017
4,5,Promoção Férias Asiáticas,"0,15",01/11/2017,31/01/2018
5,6,Promoção de Primavera Asiática,"0,2",01/02/2017,30/04/2017
6,7,Promoção de Verão Asiático,"0,1",01/05/2017,30/06/2017
7,8,Promoção de Primavera Europeia,"0,07",01/02/2017,30/04/2017
8,9,Promoção Volta às Aulas Europeias,"0,1",01/08/2017,30/09/2017
9,10,Promoção de Férias Europeias,"0,2",01/10/2017,31/01/2018
10,11,Promoção de Primavera Americana,"0,05",01/01/2018,31/03/2018
11,12,Promoção Volta às Aulas Americanas,"0,1",01/07/2018,30/09/2018
12,13,Promoção Férias Escolares Americanas,"0,2",01/11/2018,31/12/2018
13,14,Promoção Férias Asiáticas,"0,15",01/11/2018,31/01/2019
14,15,Promoção de Primavera Asiática,"0,2",01/02/2018,30/04/2018
15,16,Promoção de Verão Asiático,"0,1",01/05/2018,30/06/2018
16,17,Promoção de Primavera Europeia,"0,07",01/02/2018,30/04/2018
17,18,Promoção Volta às Aulas Europeias,"0,1",01/08/2018,30/09/2018
18,19,Promoção de Férias Europeias,"0,2",01/10/2018,31/01/2019
19,20,Promoção de Primavera Americana,"0,05",01/01/2019,31/03/2020
20,21,Promoção Volta às Aulas Americanas,"0,1",01/07/2019,30/09/2019
21,22,Promoção Férias Escolares Americanas,"0,2",01/11/2019,31/12/2019
22,23,Promoção Férias Asiáticas,"0,15",01/11/2019,31/01/2020
23,24,Promoção de Primavera Asiática,"0,2",01/02/2019,30/04/2019
24,25,Promoção de Verão Asiático,"0,1",01/05/2019,30/06/2019
25,26,Promoção de Primavera Europeia,"0,07",01/02/2019,30/04/2019
26,27,Promoção Volta às Aulas Europeias,"0,1",01/08/2019,30/09/2019
27,28,Promoção de Férias Europeias,"0,2",01/10/2019,31/01/2020

In [ ]:
#vamos renomear o e-mail para ficar claro que é do cliente

### Agora podemos começar as análises